/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.border.Border;

/**
 *
 * @author LOUISE
 */
public class MenuAdministrativoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrativoVIEW
     */
    public MenuAdministrativoVIEW() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icones/LOGO SFAC.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnGrupo = new javax.swing.JButton();
        btnFormadePagamento = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Administrativo");

        jToolBar1.setRollover(true);

        btnGrupo.setText("Grupo");
        btnGrupo.setMaximumSize(new java.awt.Dimension(120, 150));
        btnGrupo.setMinimumSize(new java.awt.Dimension(120, 150));
        btnGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGrupo);

        btnFormadePagamento.setText("Forma de Pagamento");
        btnFormadePagamento.setMaximumSize(new java.awt.Dimension(170, 250));
        btnFormadePagamento.setMinimumSize(new java.awt.Dimension(170, 120));
        btnFormadePagamento.setPreferredSize(new java.awt.Dimension(170, 21));
        btnFormadePagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormadePagamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFormadePagamento);

        btnUsuario.setText("Usuário");
        btnUsuario.setFocusable(false);
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuario.setMaximumSize(new java.awt.Dimension(120, 150));
        btnUsuario.setMinimumSize(new java.awt.Dimension(120, 150));
        btnUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("Menu Administrativo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormadePagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormadePagamentoActionPerformed
        Psq_FormadePagamentoVIEW objpsqformadepagamento = new Psq_FormadePagamentoVIEW();
        
        objpsqformadepagamento.setVisible(true);
        objpsqformadepagamento.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnFormadePagamentoActionPerformed

    private void btnGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoActionPerformed
    Psq_GrupoVIEW objtelagrupo = new Psq_GrupoVIEW();
    
    objtelagrupo.setVisible(true);
    objtelagrupo.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnGrupoActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        Psq_UsuarioVIEW objtelausuario = new Psq_UsuarioVIEW();
        
        objtelausuario.setVisible(true);
        objtelausuario.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrativoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrativoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrativoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrativoVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrativoVIEW().setVisible(true);
            }
        });
    }
    
       private static class RoundedBorder implements Border {
        
        private int radius;
        
        RoundedBorder(int radius) {
            this.radius = radius;
        }
        public Insets getBorderInsets(Component c) {
            return new Insets(this.radius+1, this.radius+1, this.radius+2, this.radius);
        }

        public boolean isBorderOpaque() {
            return true;
        }

        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            g.drawRoundRect(x,y,width-1,height-1,radius,radius);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormadePagamento;
    private javax.swing.JButton btnGrupo;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
