/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CTR.EntradaCTR;
import CTR.GrupoCTR;
import CTR.PerfilCTR;
import CTR.SaidaCTR;
import CTR.PessoaCTR;
import MODEL.EntradaMODEL;
import MODEL.GrupoMODEL;
import MODEL.PerfilMODEL;
import MODEL.SaidaMODEL;
import MODEL.PessoaMODEL;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author LOUISE
 */
public class SaidaVIEW extends javax.swing.JFrame {
    
    public String opcao ="Inserir";
    
    public static int cod_saida;
    
    //Psq_SaidaVIEW objsaidatbl;
    List<PessoaMODEL> listPessoa = null;
    List<EntradaMODEL> listEntrada = null;
    PessoaCTR objpessoa = new PessoaCTR();
    EntradaCTR objentrada = new EntradaCTR();
    int item;
    public String dataehora;
    /**
     * 
     * Creates new form SaidaVIEW
     */
    public SaidaVIEW() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icones/LOGO SFAC.png")).getImage());
        //desativacampo();
        //limparCampos();
        Coresbotoes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtCod_saida = new javax.swing.JTextField();
        txtPessoa_saida = new javax.swing.JFormattedTextField();
        lblNome_pessoa = new javax.swing.JLabel();
        lblCod_pessoa = new javax.swing.JLabel();
        btnPesquisa_pessoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");

        jLabel1.setText("Realiza Saída");

        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(new RoundedBorder(7));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel2.setText("Código da Saída:");

        jLabel3.setText("CPF Pessoa:");

        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new RoundedBorder(7));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtCod_saida.setEditable(false);

        try {
            txtPessoa_saida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnPesquisa_pessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/magnifier-1_icon-icons.com_56924 (1)_1.png"))); // NOI18N
        btnPesquisa_pessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisa_pessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtCod_saida, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPessoa_saida, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(btnPesquisa_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(203, 203, 203))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCod_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblNome_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnSalvar)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtCod_saida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPessoa_saida)
                    .addComponent(btnPesquisa_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCod_pessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNome_pessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel3))
        );

        getAccessibleContext().setAccessibleDescription("Cadastro de Usuário");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if(opcao.equals("Inserir"))
        {
           //Psq_SaidaVIEW objsaida = new Psq_SaidaVIEW();
            
           inseresaida(); 
           limparCampos();
           //objsaida.setVisible(true);
           //objsaida.setLocationRelativeTo(null);
          // objsaida.pesquisarSaida();
           this.dispose();
        }
        else if(opcao.equals("Alterar"))
        {
            //Psq_SaidaVIEW objsaida = new Psq_SaidaVIEW();
            
            alterasaida();
            limparCampos();
           // objsaida.setVisible(true);
            //objsaida.setLocationRelativeTo(null);
           // objsaida.pesquisarSaida();
            this.dispose();
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
//        Psq_SaidaVIEW psqtela = new Psq_SaidaVIEW();
//            psqtela.setVisible(true);
//            psqtela.setLocationRelativeTo(null);
//            psqtela.pesquisarSaida();
//            psqtela.setLocationRelativeTo(null);
                this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPesquisa_pessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisa_pessoaActionPerformed
        //cod_pessoa = ;
        //String nome_pessoa = ;
        listPessoa = (List<PessoaMODEL>) objpessoa.pegarPessoaBDPeloCPF(txtPessoa_saida.getText());
        
        listEntrada = objentrada.pegarUltimaEntradaBDPeloCPF(listPessoa.get(0).getCod_pessoa());
        
        lblCod_pessoa.setText(Integer.toString(listPessoa.get(0).getCod_pessoa()));       
        lblNome_pessoa.setText(listPessoa.get(0).getNome_pessoa());
        
    }//GEN-LAST:event_btnPesquisa_pessoaActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaidaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaidaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaidaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaidaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaidaVIEW().setVisible(true);
            }
        });
    }
    
    
    public void PegaDataeHora(){
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
	dataehora = new SimpleDateFormat("dd/MM/yyyy").format(timestamp.getTime());
    }
    
  
    
    public void Coresbotoes(){
    Color salvarcor = new Color(62, 123, 242);
    Color cancelarcor = new Color(242, 62, 62);
    btnSalvar.setBackground(salvarcor);
    btnCancelar.setBackground(cancelarcor);
    }
    
        public void limparCampos(){
           txtPessoa_saida.setText("");        
        }
    
    public void desativacampo(){
        txtCod_saida.setEditable(false);
    }
        
    public void inseresaida(){
        
       int perfil_selecicionado;
       
      int cod_pessoa;
        
      int saida_entrada;
              
      SaidaCTR objctr = new SaidaCTR();
        
      listPessoa = (List<PessoaMODEL>) objpessoa.pegarPessoaBDPeloCPF(txtPessoa_saida.getText());
        
      listEntrada = objentrada.pegarUltimaEntradaBDPeloCPF(listPessoa.get(0).getCod_pessoa());
      
      
      cod_pessoa = listPessoa.get(0).getCod_pessoa();
      
      saida_entrada = listEntrada.get(0).getCod_entrada();
      
//      Timestamp timestamp = new Timestamp(System.currentTimeMillis());
//	dataehora = new SimpleDateFormat("yyyy-mm-dd hh:mm:ss").format(timestamp.getTime());
//       System.out.println(""+Timestamp.valueOf(LocalDateTime.now()));
       
        objctr.insereSAIDACTR(Timestamp.valueOf(LocalDateTime.now()), 
                                saida_entrada);
    
    }
    
    
    
    
    public void alterasaida()
    {
        SaidaCTR objsaida = new SaidaCTR();
        
        int cod_pessoa;
        
      SaidaCTR objctr = new SaidaCTR();
        
      listPessoa = (List<PessoaMODEL>) objpessoa.pegarPessoaBDPeloCPF(txtPessoa_saida.getText());
        
      cod_pessoa = listPessoa.get(0).getCod_pessoa();
      
      
      Timestamp timestamp = new Timestamp(System.currentTimeMillis());
	dataehora = new SimpleDateFormat("dd/MM/yyyy").format(timestamp.getTime());
        
        
        
        objsaida.AlteraSaidaCTR(Timestamp.valueOf(dataehora), 
                                cod_pessoa,
                                cod_saida);
    
    }
    

//    public void carregaperfilcmb()
//    {
//        PerfilCTR objperfil = new PerfilCTR();
//        listPerfil = objperfil.ListaPerfilBD();
//        cmbSaida_perfil.removeAllItems();
//        int i = 0;
//        
//        while(i < listPerfil.size())
//        {
//            cmbSaida_perfil.addItem(listPerfil.get(i).getNome_perfil());
//            i++;
//        }
//        
//    }
    
    
    public void pesquisasaida(){
    SaidaCTR objctr = new SaidaCTR();
    int cod_pessoa;
    String cod_pesquisa;
              
    listPessoa = (List<PessoaMODEL>) objpessoa.pegarPessoaBDPeloCPF(txtPessoa_saida.getText());
        
    cod_pessoa = listPessoa.get(0).getCod_pessoa();
    
    
    objctr.PesquisarSAIDACTR(Integer.toString(cod_pessoa));
    }
    
    
    public void psqsaida(){
//    Psq_SaidaVIEW psqtel = new Psq_SaidaVIEW();
 //   psqtel.setVisible(rootPaneCheckingEnabled);
           
    }
    
       private static class RoundedBorder implements Border {
        
        private int radius;
        
        RoundedBorder(int radius) {
            this.radius = radius;
        }
        public Insets getBorderInsets(Component c) {
            return new Insets(this.radius+1, this.radius+1, this.radius+2, this.radius);
        }

        public boolean isBorderOpaque() {
            return true;
        }

        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            g.drawRoundRect(x,y,width-1,height-1,radius,radius);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnPesquisa_pessoa;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCod_pessoa;
    private javax.swing.JLabel lblNome_pessoa;
    public javax.swing.JTextField txtCod_saida;
    public javax.swing.JFormattedTextField txtPessoa_saida;
    // End of variables declaration//GEN-END:variables
}
